config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :posts do 
  	member do
  		put 'like', to: 'posts#upvote'
  	end
    resources :comments
  end 
  resources :users, only: [:show]
  resources :profile
  resources :friendship, only: [:destroy]
  get 'my_friends', to: "users#my_friends"
  get 'search_friends', to: "users#search"
  post 'add_friend', to: "users#add_friend"
  

  root "posts#profile"
  #root "profile#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, :class_name => 'User'
end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
  has_many :comments
	has_attached_file :image, :styles => { :medium => "300x300>"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, :styles => { :medium => "300x300>"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts 
  has_many :comments
  has_many :friendships
  has_many :friends, through: :friendships
  has_one :profile

  def not_friends_with?(friend_id)
  	friendships.where(friend_id: friend_id).count < 1
  end 

  def except_current_user(users)
  	users.reject { |user| user.id == self.id }
  	
  end 

  def self.search(param)
  	return nil if param.blank?

  	param.strip!
  	param.downcase!

  	email_matches(param).uniq
  end 


  def self.email_matches(param)
  	matches('email',param)
  end 

  def self.matches(field_name,param)
  	where("lower(#{field_name}) like?", "%#{param}%")
  end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create 
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:comment))
    @comment.user_id = current_user.id if current_user
    @comment.save 
    if @comment.save 
      redirect_to post_path(@post) 
    else
      render 'new'
    end 
  end 

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@posts)
  end 
end

app/controllers/friendship_controller.rb
class FriendshipController < ApplicationController

  def destroy
    @friendship = current_user.friendships.where(friend_id: params[:id]).first
    @friendship.destroy
    respond_to do |format|
      format.html { redirect_to my_friends_path, notice: "killed" }
    end
  end 

end 

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!, except: [:index,:show]

	def index 
	end 
	
	def profile
		@posts = Post.all.order("created_at DESC")
	end 

	def show 
	end 

	def new
		@post = current_user.posts.build
	end 

	def create
		@post = current_user.posts.build(post_params)
		#current_user.relationships 
		# implies the association of the current_user has many relationships 
    #current_user.relationships.build 
		# .build is a method to populate a new object that can be save as a new record
		# means you will create a new relationship record by populating the user_id 
		# column with the current_user.id and the followed_id with the target @user.id
		if @post.save
			redirect_to @post, notice: "Post was succesfully created"
			#redirect to @post ie th post show pages
		else
			render 'new'
		end 

	end 

	def edit 
	end 

	def update
		if @post.update(post_params)
			redirect_to @post, notice: "Post was succesfully updated"
		else 
			render 'edit'
		end 
	end 

	def destroy
		@post.destroy
		redirect_to root_path
	end 

	def upvote 
		@post.upvote_by current_user
		redirect_to :back
	end 

	private 

	def post_params
		params.require(:post).permit(:title,:description, :image)
	end 

	def find_post
		@post = Post.find(params[:id])
	end 

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :find_profile, only: [:show, :edit, :update, :destroy, :new, :update]
  before_action :authenticate_user!

  def index 
  end 

  def show 
    @profile = Profile.find(params[:id])
  end 

  def new
    @profile = current_user.profile.build
  end 

  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    if @profile.save
      redirect_to @profile, notice: "profile created"
    else 
      render "new"
    end 
  end

  def edit 

  end 

  def update 
    #if @profile.update(profiles_params)
     # redirect_to @profile, notice: "profile updated"
    #else
     # render "edit"
    #end
    @profile = Profile.find(params[:id])
    if @profile.update(profile_params)
      redirect_to @profile
    else
    render 'edit'
  end 
  end 

  def destroy
  end

  private 

  def profiles_params
    params.require(:profile).permit(:name,:about, :image)
  end 

  def find_profile
    @profile = Profile.find(params[:id])
  end 


end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

	protected

	def after_sign_in_path_for resource
		"/pins/#{current_user.id}/profile"
	end
end

app/controllers/users/users_controller.rb
class UsersController < ApplicationController

	def my_profile
		@user = current_user
	end 

	def my_friends
	end 
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def my_profile
		@user = current_user
	end 

	def my_friends
		@friendships = current_user.friends
		@users = User.search(params[:search_param])
		#@search_params = params[:search_params]
		if @users
			@users = current_user.except_current_user(@users)
		end 
	end 

	def show 
		@user = User.find(params[:id])
	end 

	def search 
		@users = User.search(params[:search_param])
		#@search_params = params[:search_params]
		if @users
			@users = current_user.except_current_user(@users)
		end 

	end 

	def add_friend
		@friend = User.find(params[:friend])
		#binding.pry
		current_user.friendships.build(friend_id: @friend.id)
		#current_user.relationships 
		# implies the association of the current_user has many relationships 
		#current_user.relationships.build 
		# .build is a method to populate a new object that can be save as a new record
		# means you will create a new relationship record by populating the user_id 
		# column with the current_user.id and the followed_id with the target @user.id

		if current_user.save 
			redirect_to 'my_friends_path', notice: "Friend added"
		else
			redirect_to 'my_friends_path', flash[:error]
		end 
	end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/comments/_comment.html.erb
<body>
<p style="margin-left:20px"><%= comment.comment %>
  <span>
    <b><%= comment.user.email %></b>
    <%#= link_to "Edit" , edit_post_comment_path(comment.post, comment) %>
    <%= link_to "remome comment" , [comment.post, comment], method: :delete %> 
  </span>
</p>


</body>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
  <%= f.input :comment, input_html: {class: 'form-control'} %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/comments/edit.html.erb
<h3>Edit reply</h3>
<%#= simple_form_for([@post, @comment]) do |f| %>
  <%#= f.input :comment, input_html: {class: 'form-control'} %>
  <%#= f.button :submit, class: "btn btn-primary" %>
<%# end %>

app/views/friends/_lookup.html.erb
<div class="friends_lookup">
	<h4>Search for friends</h4>
	<%form_tag search_friends_path, remote: true, :method :get, id: 'friend-lookup-form' do %>
	<div class="form-group row no-padding text-center col-md-12" >
		<div class="col-md-10">
			<%= text_feild_tag :search_param, params[:search_param],
		placeholder: "first name , last name or email",
		autofocus: true,
		class: "form-control search-box input-lg" %>

		</div>
		<div class="col-md-2">
			<%=button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
				<i class="fa fa-search"></i>Search
			<% end %>
		</div>
	</div>
	<% end %>
	<% if @users %>
		<% if @users.size >0 %>
			<div id="friend-lookup-results" class="well results-block col-md-10">
				<table class="search-results-table col-md-12">
					<tbody>
						<% users.each do |user| %>
							<tr>
								<td><strong>Name:</strong><%= user.full_name %></td>
								<td><strong>Email:</strong><% user.email %></td>
								<td><strong>Profile:</strong><%= link_to "View Profile", user_path(user), class: "btn btn-xs btn-success" %>
								<% if current_user.not_friends_with?(user.id) %>
									<%= link_to "Add Friend", add_friend_path(user: current_user, friend: user), class: "btn btn-xs btn-success", method: :post %>
								<% else %> 
									<span class="label label-primary">
										You are friends
									</span>
								<% end %>
								</td>
							</tr>
						<% end %>	
					</tbody>
				</table>
			</div>
		<% else %>
			<p clall="lead col-md-12">No match to this search </p>
		<% end %>
	<% end %>
	<div id="friends-lookup-errors"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ComicCon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<style>
	.colorlink{
		color: yellow;
	}
</style>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class="navbar-brand">
      	<%= link_to "ComicCon", root_path, :class => 'colorlink' %>
      </div>
    </div>
    <div class="sider">
	    <ul class="nav navbar-nav">
	      <li class="active"><%= link_to 'Home', posts_path%></li>
	      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">About<span class="caret"></span></a>
	        <ul class="dropdown-menu">
	          <li><a href="#">ComicCon</a></li>
	          <li><a href="#">Events</a></li>
	          <li><a href="#">NewsFeed</a></li>
	        </ul>
	      </li>
	    </ul>
	    <% if user_signed_in? %>
	    	<ul class="nav navbar-nav navbar-right">
	    		<li><%= link_to 'Friends', my_friends_path, :class => 'navbar-link'%></li>
          <li><%= link_to 'Profile', profile_path(current_user), :class => 'navbar-link'%></li>
					<li><%= link_to 'New Character', new_post_path, :class => 'navbar-link'%></li>
					<li><%= link_to 'account', edit_user_registration_path, :class => 'navbar-link'%></li>
					<li><%= link_to 'Sign out', destroy_user_session_path, method: :delete, :class => 'navbar-link'%>
					</li>
				</ul>
			<% else %>
		    <ul class="nav navbar-nav navbar-right">
		      <li><span class="glyphicon glyphicon-user"></span><%= link_to 'Sign Up', new_user_registration_path, :class => 'navbar-link'%></li>
		      <li><span class="glyphicon glyphicon-log-in"></span><%= link_to 'Sign In', new_user_session_path, :class => 'navbar-link'%></li>
		    </ul>
		  <% end %>
    </div>
  </div>
</nav>


<div class="container">
<%# this is for the flash notice %>
<% flash.each do |name, msg| %>
	<%= content_tag :div, msg, class: "alert alert-info" %>
<% end %>
<%= yield %>

</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post, html: {multipart: true} ) do |f| %>
<%#this is for the image uploading%>
	<% if @post.errors.any? %>
		<div id="error_explanation">
			<h2> <%= pluralize(@post.errors.count, "error") %>
			This post shall be preventd from saving </h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form-group">
		<%= f.input :image, input_html: {class: 'form-control'} %>
		<%= f.input :title, input_html: {class: 'form-control'} %>
		<%= f.input :description, input_html: {class: 'form-control'} %>
		<%= f.button :submit,  class: "btn btn-primary" %>
	</div>

<% end %>

app/views/posts/_userpost.html.erb
<div class="col-md-2"></div>
<div class="col-md-8">
<div id="masonry-container" class="transitions-enabled centered clearfix masonry">
  <div class="row" style="background-color:#d8d5d208">
    <% obj.each do |post| %>
        <div class="box col3 panel panel-default">
          <%= image_tag post.image.url %><br>
          <div class="panel-body">  
            <b style="color:red;font-weight:bold"><%= link_to post.title , post %></b>
          </div>
        </div>
    <% end %>
  </div>
</div>
</div>
<div class="col-md-2"></div>

app/views/posts/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<h1>Edit</h1>
	<%= image_tag @post.image.url(:medium) %>
	<%= render "form" %>
	<%= link_to "Back", root_path %>
	<%= link_to "Cancel", post_path %>
</div>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 70%;
      margin: auto;
  }
  body {
    background-image: url("/assets/bck2.jpg"); 
    background-repeat: repeat-y;
  }
  </style>
</head>
<body>
<!-- <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#" style="color:yellow">ComicCon</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Page 1-1</a></li>
          <li><a href="#">Page 1-2</a></li>
          <li><a href="#">Page 1-3</a></li>
        </ul>
      </li>
      <li><a href="#">Page 2</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>
 -->
<div class="container">
  <br>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
      <li data-target="#myCarousel" data-slide-to="4"></li>
      <li data-target="#myCarousel" data-slide-to="5"></li>
      <li data-target="#myCarousel" data-slide-to="6"></li>
     
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="/assets/1.jpg" alt="Chania" width="460" height="345">
      </div>

      <div class="item">
        <img src="/assets/9.jpg" alt="Chania" width="400" height="305">
      </div>
      <div class="item">
        <img src="/assets/7.jpg" alt="Chania" width="400" height="305">
      </div>
      <div class="item">
        <img src="/assets/6.jpg" alt="Chania" width="400" height="305">
      </div><div class="item">
        <img src="/assets/5.jpg" alt="Chania" width="400" height="305">
      </div>
      <div class="item">
        <img src="/assets/10.jpg" alt="Chania" width="400" height="305">
      </div>
      <div class="item">
        <img src="/assets/01.png" alt="Chania" width="400" height="305">
      </div>
      
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

</body>
</html>

app/views/posts/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h1>Post Character</h1>
				<%= render "form" %>
			</div>
		</div>
	</div>
</div>

app/views/posts/profile.html.erb
<style>
.box{
	background: none;
	background-color: transparent
}
.panel{
	border:none;
	border-radius:none
}
.col3{width:180px;}
</style>
<h3 align="center">Characters</h3>
<%= render 'userpost', obj: @posts %>

app/views/posts/show.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="panel panel-default">
			<div class="panel-heading" style="background-image: url('/assets/warzone1.jpg');
    width:748px;
    height:331px;">
				<p><%= image_tag @post.image.url(:medium) %></p>
			</div>
			<div class="panel-body">
				<h1> 
					<%= @post.title %>  
				</h1>
				<p> 
					<%= @post.description %>
	 			</p>
 			</div>
 			<div class="panel-footer">
 				<div class="row">
 					<div class="col-md-6">
			 			<p>
			 			<%= @post.user.email if @post.user %>
			 			</p>
			 		</div>
	 				<div class="col-md-6">
	 					<div class="btn-group pull-right">
	 					<%= link_to "Like", like_post_path, method: :put, :class => 'btn btn-default', :class => 'btn btn-default' %> 
	 						<span style="margin-left:20px" class="glyphicon glyphicon-heart">
	 							<%= @post.get_upvotes.size %>
	 						</span>
	 						<% if user_signed_in? %>
					 			<%= link_to "Back" , root_path , :class => 'btn btn-default'%>
								<%= link_to "Edit", edit_post_path, :class => 'btn btn-default' %> 
								<%= link_to "delete", post_path, method: :delete, data: { confirm: "are you sure ?"}, :class => 'btn btn-default' %>
							<% end %>
						</div>
					</div>
				</div>
				<div class="row">
				<h2><% @post.comments.count %></h2>
				<%= render @post.comments %>

				<%= render "comments/form" %>
				</div>
			</div>

		</div>
	</div>
</div>

app/views/users/_lookup.html.erb
<div class="friends_lookup">
	<h4>Search for friends</h4>
	<%= form_tag my_friends_path, :method => :get, :id => 'friend-lookup-form' do %>
	<div class="form-group row no-padding text-center col-md-12" >
		<div class="col-md-10">
			<%= text_field_tag :search_param, params[:search_param],placeholder: "email",autofocus: true, class: "form-control search-box input-lg" %>
		</div>
		<div class="col-md-2">
			<%=button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
				<i class="fa fa-search"></i>Search
			<% end %>
		</div>
	</div>
	<% end %>
	<% if @users %>
		<% if @users.size > 0 %>
			<div id="friend-lookup-results" class="well results-block col-md-10">
				<table class="search-results-table col-md-12">
					<tbody>
						<% @users.each do |user| %>
							<tr>
								<td><strong>Email:</strong><%= user.email %></td>
								<td><strong>Profile:</strong><%= link_to "View Profile", user_path(user), class: "btn btn-xs btn-success" %>
								<% if current_user.not_friends_with?(user.id) %>
									<%= link_to "Add Friend", add_friend_path(user: current_user, friend: user), class: "btn btn-xs btn-success", method: :post %>
								<% else %> 
									<span class="label label-primary">
										yo ! You are friends
									</span>
								<% end %>
								</td>
							</tr>
						<% end %>	
					</tbody>
				</table>
			</div>
		<% else %>
			<p clall="lead col-md-12">No match to this search </p>
		<% end %>
	<% end %>
	<div id="friends-lookup-errors"></div>
</div>

app/views/users/my_friends.html.erb
<%= render 'users/lookup' %>

<% if @friendships.size > 0 %>
	<div class="col-md-8">
		<%#= render "lookup" %> 
		<table class="table table-striped">
			<thead>
				<tr>
					<th colspan="3" class="page-header">
						<h2> Friends </h2>
					</th>
				</tr>
				<tr>
					<td>Email</td>
		      <td>Action</td>
				</tr>
			</thead>
			<tbody>
				<% @friendships.each do |friend| %>
					<tr>
						<td><%= friend.email %></td>
						<td>
							<%= link_to "View Profile", user_path(friend), class:'btn btn-primary btn-xs' %>
							<%= link_to "Unfriend", friendship_path(friend), 
							              :method => :delete,
							              class:'btn btn-xs btn-danger'%>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>

<% else %>
	<div class="row col-lg-12">
		<p> you don't have friends :P </p>
	</div>

<% end %>

app/views/users/show.html.erb
<style>
.box{
  background: none;
  background-color: transparent
}
.panel{
  border:none;
  border-radius:none
}
.col3{width:180px;}
</style>m
<h3><%= current_user.email.split('@')[0] %></h3>
<%# render profile/show(@user ie the current_user) %>
<%= link_to "update profile", new_profile_path, method: :put, :class => 'btn btn-default', :class => 'btn btn-default' %> 
<div class="panel-body">
  <h1> 
    <%#= current_user.profile.name %>  
  </h1>
  <p> 
    <%#= @profile.about %>
  </p>
</div>
<%= render 'posts/userpost', obj: @user.posts %>